stages:
  - build
  - deploy
  - tags_push

##########  -  develop  -  ##########
build-image-develop:
  stage: build
  only:
    - develop
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:develop .

deploy-develop:
  stage: deploy
  only:
    - develop
  script:
    - docker rm -f hcare_frontend-dev || true
    - docker run -d -p 8080:80 --name hcare_frontend-dev --env-file ./hcare/.env --restart=always $CI_REGISTRY_IMAGE:develop
  when: manual


##########  -  master  -  ##########

####################################

##########  -  tag  -  ##########
tags-push-image:
  stage: tags_push
  only:
    - tags
  except:
    - branches
  script:
    - docker build --pull --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG


after_script:
  - docker ps
