# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
CMD ["echo", "$FIREBASE_DEPLOY_KEY"]
# COPY ./hcare/package*.json ./
# RUN npm install && npm install -g firebase-tools
# COPY ./hcare/ .
# RUN yarn build
# RUN firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY